### ISSUE TITLE
File extension

### ISSUE THREAD

**Issue by maslyankov** [eriksundin/appicon#3]
Great app!!! The only issue I find is that it converts the image files to the wrong file format. It makes them JPEG, when they should be PNG.

**Comment by maslyankov** [comment]
Edit: This only happens if you use a JPEG as a source image for generating. Therefore I suggest as a improvement - check if the source is PNG, if not - convert and then scale.

**Comment by eriksundin** [comment]
Hi @maslyankov, great that you're using the tool and am happy with it.
The idea is to keep the tool as simple as possible, and keeping the image type in the generation process is a conscious decision. I want it to work as expected, just rescaling images - no more no less. So PNGs in, PNGs out and so forth.

Kind Regards,
Erik
